dist: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

notifications:
  email: false

script: ./scripts/ci/build-and-test.sh

deploy:
  - provider: script
    script: ./scripts/ci/deploy.sh
    skip_cleanup: true
    on:
      branch: docker
